app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    if(Auth::User()){
		return redirect()->route('admin.inicio');
    }else{
		return redirect()->route('auth.login');
    }
});


Route::group(['middleware' => 'auth'],function(){
	Route::get('inicio',['as' => 'admin.inicio', function () {
		return view('inicio');
	}]);

	Route::resource('usuarios','UsuarioController');
	Route::resource('departamentos','DepartamentoController');
	Route::resource('personas','PersonaController');
	Route::resource('tareas','TareasController');
	Route::resource('tareas','TareasController');
	Route::resource('detalles_tareas','Detalle_tareaController');
	Route::get('listaTareas/{id?}','TareasController@listaTareas');
	Route::get('listaTareas/{id?}', [  /*Ruta para mostrar la tabla donde se crea la tarea*/
                'uses' => 'TareasController@listaTareas',
                'as' => 'listaTareas'
                ]);
	Route::get('descarga/{id?}', [  
                'uses' => 'TareasController@descarga',
                'as' => 'descargarTarea'
                ]);
	Route::get('detalleTarea/{id?}/{opcion?}', [  
                'uses' => 'TareasController@detalleTareas',
                'as' => 'detalleTareas'
                ]);
	Route::post('correo/enviar', [  
                'uses' => 'CorreoController@enviarCorreo',
                'as' => 'enviarCorreo'
                ]);
	Route::get('correo/cargarArchivo', [ 
                'uses' => 'CorreoController@cargarArchivo',
                'as' => 'cargarArchivo'
                ]);
		Route::get('correo/nuevoCorreo', [  
                'uses' => 'CorreoController@nuevoCorreo',
                'as' => 'nuevoCorreo'
                ]);
	Route::post('actualizar', [  
                'uses' => 'CorreoController@actualizar',
                'as' => 'actualizar'
                ]);

});

Route::get('auth/login', [
	'uses' => 'Auth\AuthController@getLogin',
	'as' => 'auth.login'
]);
Route::post('auth/login', [
	'uses' => 'Auth\AuthController@postLogin',
	'as' => 'auth.login'
]);
Route::get('auth/logout', function(){
	Auth::logout();
    return redirect()->route('auth.login');
});

app/Models/Tarea.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tarea extends Model
{
     protected $table= 'tareas';
    protected $primarykey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'emisor','receptor', 'asunto', 'estado', 'contenido','archivo'
    ];

}

app/Http/Controllers/TareasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\Tarea;
use App\Models\DetalleTarea;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use Illuminate\Http\UploadedFile;


class TareasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        if ($id==1) {
            return view('tareas.index');
        }else{
            dd('hola');
        }

    }

    public function listaTareas($id)
    {
        if ($id==1) {
            $tareas = Tarea::select('*')->where('emisor', '=', Auth::user()->email)->get();
            return view('tareas.index')->with('tareas',$tareas)->with('opcion',1);
        }else{
            $tareas = Tarea::select('*')->where('receptor', '=', Auth::user()->email)->get();
            return view('tareas.index')->with('tareas',$tareas)->with('opcion',2);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tarea= new Tarea();
        return view('tareas.create')->with('tarea',$tarea);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->file("archivo")->getClientOriginalName());
        $aleatorio = str_random(6);
        $nombre = $aleatorio.'-'.$request->file("archivo")->getClientOriginalName();
        $request->file("archivo")->move('archivos',$nombre);

        Tarea::create([
                'emisor'        => Auth::user()->email,
                'receptor'      => $request['receptor'],
                'asunto'        => $request['asunto'],
                'estado'        => 'en_proceso',
                'contenido'     => $request['contenido'],
                'archivo'       => $nombre
        ]);

        $pathToFile="";
        $containfile=false; 
        $redireccionar=false;
        if($request->hasFile('archivo') ){
            if ($request['id_tarea']) {
                $redireccionar=true;
            }
            $containfile=true; 
            $aleatorio = str_random(6);
            $nombre = $aleatorio.'-'.$request->file("archivo")->getClientOriginalName();
            $request->file("archivo")->move('archivos',$nombre);
            $file = $request->file('archivo');
            $pathToFile= public_path()."/archivos/".$nombre;
        }

        if($request['id_tarea'] && !$request->hasFile('archivo')){
            $tarea=Tarea::findOrFail($request['id_tarea']);
            $containfile=true;
            $nombre = $tarea->archivo;
            $pathToFile= public_path()."/archivos/".$nombre;
            $redireccionar=true;
        }
        $destinatario=$request->input("receptor");
        $asunto=$request->input("asunto");
        $contenido=$request->input("contenido");


        $data = array('contenido' => $contenido);
        $r= Mail::send('correos.plantilla_correo', $data, function ($message) use ($asunto,$destinatario,  $containfile,$pathToFile) {
            $message->from('cvgfundeportepzo@gmail.com', 'funi567890');
            $message->to($destinatario)->subject($asunto);
            if($containfile){
                $message->attach($pathToFile);
            }

        });
        
        // $name = Carbon::now().$request->file("archivo")->getClientOriginalName();
        // $request->file("archivo")->move('archivos',$name);
        // dd('terminado');
        // return redirect()->route('tareas.index');

        return redirect()->route('listaTareas',"1");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        dd($id);
        $tarea= Tarea::findOrFail($id);
        $archivo= explode("-", $tarea->archivo);
        $archivo = $archivo[1];
        return view('tareas.editar')->with('tarea', $tarea)->with('archivo',$archivo);
    }

    protected function downloadFile($src){
        if(is_file($src)){
            $finfo = finfo_open(FILEINFO_MIME_TYPE);
            $content_type = finfo_file($finfo, $src);
            finfo_close($finfo);
            $file_name = basename($src).PHP_EOL;
            $size = filesize($src);
            header("Content-Type: $content_type");
            header("Content-Disposition: attachment; filename=$file_name");
            header("Content-Transfer-Encoding: binary");
            header("Content-Length: $size");
            readfile($src);
            return true;
        } else{
            return false;
        }
    }

    public function descarga($id)
    {
        if(!$this->downloadFile(public_path()."/archivos/".$id)){
            return redirect()->back();
        }
    }


    public function detalleTareas($id,$opcion)
    {
        $tarea= Tarea::findOrFail($id);
        $archivo= explode("-", $tarea->archivo);
        $archivo = $archivo[1];
        return view('tareas.edit')->with('tarea', $tarea)->with('archivo',$archivo)->with('opcion',$opcion);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         dd($request);
    }

    public function actualizar(Request $request)
    {
        dd($request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $tarea = Tarea::FindOrFail($request['id']);
        $tarea->delete();
        return redirect()->route('listaTareas',$request['opcion']);
    }
}

resources/views/tareas/_form.blade.php
@if ($tarea->exists)
    <form id="frmFileUpload" class="dropzone" action={{ route('tareas.update',  $tarea->id) }} method="POST" enctype="multipart/form-data">
    {{ method_field('PUT') }}
@else
    <form enctype="multipart/form-data" class="dropzone" action={{ route('tareas.store') }} method="POST">
@endif
        {{csrf_field()}}
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Nueva Tarea
                        </h2>
                    </div>
                    <div class="body">
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">Para</h2>
                                <input type="email" class="form-control" name="receptor" placeholder="ejemplo@gmail.com" value="" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">Asunto</h2>
                                <input type="text" class="form-control" name="asunto" value="" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <div>
                                <input type="file" class="form-control" name="archivo" id="archivo" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">Contenido</h2>
                                <textarea rows="8" class="form-control" name="contenido"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <button type="submit" class="btn btn-lg btn-block bg-blue waves-effect waves-light" name="">
                                Enviar
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# CKEditor -->


            
        </div>
    </section>
    </form>

resources/views/tareas/_form2.blade.php
@if($opcion!=3)
<form enctype="multipart/form-data" id="form-tareas" action={{ route('actualizar') }} method="POST">
    @else
    <form enctype="multipart/form-data" id="form-tareas" action={{ route('enviarCorreo') }} method="POST">
        @endif
        {{csrf_field()}}
        <input type="hidden" name="id_tarea" value="{{$tarea->id}}">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Detalle de Tarea
                        </h2>
                    </div>
                    <div class="body">
                        @if($opcion==1 || $opcion==3)
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">Para</h2>
                                <input type="email" class="form-control quitar" name="receptor" placeholder="ejemplo@gmail.com" value="{{$tarea->receptor}}" required="true" />
                            </div>
                        </div>
                        @elseif($opcion==2)
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">De</h2>
                                <input type="email" class="form-control quitar" name="receptor" placeholder="ejemplo@gmail.com" value="{{$tarea->emisor}}" required  />
                            </div>
                        </div>
                        @endif
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">Asunto</h2>
                                <input type="text" class="form-control quitar" name="asunto" value="{{$tarea->asunto}}" required />
                            </div>
                        </div>
                        @if($opcion!=3)
                        <div class="form-group">
                            <div>
                                <h2 class="card-inside-title">Archivo</h2>
                                <label>{{$archivo}}</label>
                                <a href={{ route('descargarTarea', $tarea->archivo) }} class="btn bg-green" style="margin-left: 50px">Descargar<i class="fa fa-download" aria-hidden="true"></i></a>
                                <input type="file" class="form-control hidden" name="archivo" id="archivo"/>
                            </div>
                        </div>
                        @else
                        <div class="form-group">
                            <div>
                                <h2 class="card-inside-title">Archivo</h2>
                                <input type="file" class="form-control" name="archivo" id="archivo" />
                            </div>
                        </div>
                        @endif
                        @if($opcion==1)
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">Estado</h2>
                                <select name="estado" class="form-control quitar">
                                  <option value="en_proceso" {{ ($tarea->estado == 'en_proceso')? 'selected':'' }}>
                                      En Proceso
                                  </option>
                                  <option value="terminado" {{ ($tarea->estado == 'terminado')? 'selected':'' }}>
                                      Terminado
                                  </option>
                              </select>
                          </div>
                      </div>
                      @endif
                      <div class="form-group">
                        <div class="form-line">
                            <h2 class="card-inside-title">Contenido</h2>
                            <textarea rows="8" class="form-control quitar" name="contenido" >{{$tarea->contenido}}</textarea>
                        </div>
                    </div>
                </div>
                @if($opcion!=2)
                <div class="footer">
                    <button type="submit" class="btn btn-lg btn-block bg-blue waves-effect waves-light" name="">
                        Enviar
                    </button>
                </div>
                @endif
            </div>
        </div>
    </div>
</form>

@if($opcion == 1 || $opcion == 2)
@section('js')
<script src={{ URL::asset('js/miscript.js') }}></script>
@endsection
@endif

resources/views/tareas/_form3.blade.php
@if($opcion!=3)
<form enctype="multipart/form-data" id="form-tareas" action={{ route('actualizar') }} method="POST">
    @else
    <form enctype="multipart/form-data" id="form-tareas" action={{ route('enviarCorreo') }} method="POST">
        @endif
        {{csrf_field()}}
        <input type="hidden" name="id_tarea" value="{{$tarea->id}}">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Detalle de Tarea
                        </h2>
                    </div>
                    <div class="body">
                        @if($opcion==1 || $opcion==3)
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">Para</h2>
                                <input type="email" class="form-control quitar" name="receptor" placeholder="ejemplo@gmail.com" value="{{$tarea->receptor}}" required="true" />
                            </div>
                        </div>
                        @elseif($opcion==2)
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">De</h2>
                                <input type="email" class="form-control quitar" name="receptor" placeholder="ejemplo@gmail.com" value="{{$tarea->emisor}}" required  />
                            </div>
                        </div>
                        @endif
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">Asunto</h2>
                                <input type="text" class="form-control quitar" name="asunto" value="{{$tarea->asunto}}" required />
                            </div>
                        </div>
                        @if($opcion!=3)
                        <div class="form-group">
                            <div>
                                <h2 class="card-inside-title">Archivo</h2>
                                <label>{{$archivo}}</label>
                                <a href={{ route('descargarTarea', $tarea->archivo) }} class="btn bg-green" style="margin-left: 50px">Descargar<i class="fa fa-download" aria-hidden="true"></i></a>
                                <input type="file" class="form-control hidden" name="archivo" id="archivo"/>
                            </div>
                        </div>
                        @else
                        <div class="form-group">
                            <div>
                                <h2 class="card-inside-title">Archivo</h2>
                                <input type="file" class="form-control" name="archivo" id="archivo" />
                            </div>
                        </div>
                        @endif
                        @if($opcion==1)
                        <div class="form-group">
                            <div class="form-line">
                                <h2 class="card-inside-title">Estado</h2>
                                <select name="estado" class="form-control quitar">
                                  <option value="en_proceso" {{ ($tarea->estado == 'en_proceso')? 'selected':'' }}>
                                      En Proceso
                                  </option>
                                  <option value="terminado" {{ ($tarea->estado == 'terminado')? 'selected':'' }}>
                                      Terminado
                                  </option>
                              </select>
                          </div>
                      </div>
                      @endif
                      <div class="form-group">
                        <div class="form-line">
                            <h2 class="card-inside-title">Contenido</h2>
                            <textarea rows="8" class="form-control quitar" name="contenido" >{{$tarea->contenido}}</textarea>
                        </div>
                    </div>
                </div>
                @if($opcion!=2)
                <div class="footer">
                    <button type="submit" class="btn btn-lg btn-block bg-blue waves-effect waves-light" name="">
                        Enviar
                    </button>
                </div>
                @endif
            </div>
        </div>
    </div>
</form>

@if($opcion == 1 || $opcion == 2)
@section('js')
<script src={{ URL::asset('js/miscript.js') }}></script>
@endsection
@endif

resources/views/tareas/_modal.blade.php
<div class="modal fade" id="mdModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action={{ route('tareas.destroy', "-1") }} method="POST">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">¿Esta seguro que desea eliminar esta tarea?</h4>
                </div>
                <div class="modal-body"> 
                    <input type="hidden" id="id-eliminar" name="id" value="">
                    <input type="hidden" id="opcion-eliminar" name="opcion">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-link waves-effect">¡ELIMINAR!</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CERRAR</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/tareas/_table.blade.php
<div class="row clearfix">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="card">
			<div class="header">
				<h2>
					Lista de tareas
				</h2>
			</div>
			<input type="text" class="hidden" id="opcion" value={{$opcion}} name="">
			<div class="body">
				<table class="table table-bordered table-striped table-hover js-basic-example dataTable">
					<thead>
						<tr>
							<th>Emisor</th>
							<th>Receptor</th>
							<th>Asunto</th>
							<th>
								<a class="btn bg-teal btn-block btn-xs waves-effect" href={{route('tareas.create')}}>
    								<i class="fa fa-plus" title="Agregar departamento"></i>
    							</a>
							</th>
						</tr>
					</thead>
					<tbody>
						@foreach($tareas as $tarea)
							<tr>
								<td>{{$tarea->emisor}}</td>
								<td>{{$tarea->receptor}}</td>
								<td>{{$tarea->asunto}}</td>
								<td>
									<div class="btn-toolbar">
										<div class="btn-group btn-circle">
											<a class="btn bg-blue btn-circle waves-effect waves-circle waves-float" href={{ route('detalleTareas', [$tarea->id,$opcion] ) }}>
    											<i class="fa fa-info" title="Informacion de Tarea"></i>
    										</a>
										</div>                           
										@if($opcion==1)
											<div class="btn-group btn-circle">
												<a class="btn bg-green btn-circle waves-effect waves-circle waves-float" href={{ route('detalleTareas', [$tarea->id,3] ) }}>
													<i class="fa fa-send" title="Enviar Tarea Por Correo"></i>
												</a>
											</div>
											<div class="js-modal-buttons btn-group btn-circle">
												<button value={{$tarea->id}} type="button" data-color='red' class=" btn eliminar bg-red btn-circle waves-effect waves-circle waves-float ">
													<i class="fa fa-trash" title="Eliminar Tarea"></i>
												</button>
											</div>
										@endif
									</div>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>


@section('js')
	<script src={{ URL::asset('js/miscript.js') }}></script>
@endsection

resources/views/tareas/create.blade.php
@extends ('template.main')
@section('title', 'Crear Tarea')
@section ('contenido')

	<!-- Input -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                        	<h1>Nueva Tarea</h1>
                        </div>
                        <div class="body">
                            @include('tareas._form',['tarea'=>$tarea])
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Input -->
	
@endsection

resources/views/tareas/edit.blade.php
@extends ('template.main')
@section('title', 'Detalle de Tarea')
@section ('contenido')

<!-- Input -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
               <h1>Detalle de las tareas</h1>
           </div>
           <div class="body">
            @if($opcion==1)
                @include('tareas._form3',[ 'tarea' => $tarea, 'archivo' => $archivo])
            @else
                @include('tareas._form2',[ 'tarea' => $tarea, 'archivo' => $archivo, 'opcion' => $opcion])
            @endif
            </div>
    </div>
</div>
<!-- #END# Input -->

@endsection

resources/views/tareas/index.blade.php
@extends ('template.main')
@section('title', 'Lista de departamentos')
@section ('contenido')

@include('tareas._modal')
@include('tareas._table',[ 'tareas' => $tareas, 'opcion' => $opcion])
	
@endsection