app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    if(Auth::User()){
		return redirect()->route('admin.inicio');
    }else{
		return redirect()->route('auth.login');
    }
});


Route::group(['middleware' => 'auth'],function(){
	Route::get('inicio',['as' => 'admin.inicio', function () {
		return view('inicio');
	}]);

	Route::resource('usuarios','UsuarioController');
	Route::resource('departamentos','DepartamentoController');
	Route::resource('personas','PersonaController');
	Route::resource('tareas','TareasController');
	Route::resource('tareas','TareasController');
	Route::resource('detalles_tareas','Detalle_tareaController');
	Route::get('listaTareas/{id?}','TareasController@listaTareas');
	Route::get('listaTareas/{id?}', [  /*Ruta para mostrar la tabla donde se crea la tarea*/
                'uses' => 'TareasController@listaTareas',
                'as' => 'listaTareas'
                ]);
	Route::get('descarga/{id?}', [  
                'uses' => 'TareasController@descarga',
                'as' => 'descargarTarea'
                ]);
	Route::get('detalleTarea/{id?}/{opcion?}', [  
                'uses' => 'TareasController@detalleTareas',
                'as' => 'detalleTareas'
                ]);
	Route::post('correo/enviar', [  
                'uses' => 'CorreoController@enviarCorreo',
                'as' => 'enviarCorreo'
                ]);
	Route::get('correo/cargarArchivo', [ 
                'uses' => 'CorreoController@cargarArchivo',
                'as' => 'cargarArchivo'
                ]);
		Route::get('correo/nuevoCorreo', [  
                'uses' => 'CorreoController@nuevoCorreo',
                'as' => 'nuevoCorreo'
                ]);
	Route::post('actualizar', [  
                'uses' => 'CorreoController@actualizar',
                'as' => 'actualizar'
                ]);

});

Route::get('auth/login', [
	'uses' => 'Auth\AuthController@getLogin',
	'as' => 'auth.login'
]);
Route::post('auth/login', [
	'uses' => 'Auth\AuthController@postLogin',
	'as' => 'auth.login'
]);
Route::get('auth/logout', function(){
	Auth::logout();
    return redirect()->route('auth.login');
});

app/Models/Persona.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Persona extends Model
{
    protected $table= 'personas';
    protected $primarykey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre','apellido', 'cedula', 'email', 'departamento_id',
    ];


    public function departamento(){
        return $this->belongsTo(Departamento::class,'departamento_id', 'id');
    }



}

app/Http/Controllers/PersonaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\Persona;
use App\Models\Departamento;

class PersonaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $personas=Persona::all();
        return view('personas.index')->with('personas',$personas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $persona = new Persona();
        $departamentos=Departamento::all();
        return view('personas.create')->with('persona', $persona)->with('departamentos',$departamentos);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request['departamento_id']==0) {
            return redirect()->route('personas.create');
        }

        Persona::create([
                'nombre' => $request['nombre'],
                'apellido' => $request['apellido'],
                'cedula' => $request['cedula'],
                'email' => $request['email'],
                'departamento_id' => $request['departamento_id']
        ]);
        return redirect()->route('personas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $persona = Persona::findOrFail($id);
        $departamentos=Departamento::all();
        return view('personas.edit')->with('persona',$persona)->with('departamentos',$departamentos);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $persona = Persona::FindOrFail($id);
        $input = $request->all();
        $persona->fill($input)->save();
        return redirect()->route('personas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $persona = Persona::FindOrFail($request['id']);
        $persona->delete();
        return redirect()->route('personas.index');
    }
}

resources/views/personas/_form.blade.php
@if ($persona->exists)
    <form id="form-personas" class="" action={{ route('personas.update',  $persona->id) }} method="POST">
    {{ method_field('PUT') }}
@else
    <form id="form-personas" class="" action={{ route('personas.store') }} method="POST">
@endif

    <div class="row clearfix">
        <div class="col-sm-12">
            <div class="form-group">
                <div class="form-line">
                    <h2 class="card-inside-title">Nombre</h2>
                    <input type="text" class="form-control" name="nombre" placeholder="ej: Juan" value="{{$persona->nombre}}" />
                </div>
            </div>
            <div class="form-group">
                <div class="form-line">
                    <h2 class="card-inside-title">Apellido</h2>
                    <input type="text" class="form-control" name="apellido" placeholder="ej: Guzman" value="{{$persona->apellido}}" />
                </div>
            </div>
            <div class="form-group">
                <div class="form-line">
                    <h2 class="card-inside-title">Cedula</h2>
                    <input type="text" class="form-control" name="cedula" placeholder="ej: 12345" value="{{$persona->cedula}}"/>
                </div>
            </div>
            <div class="form-group">
                <div class="form-line">
                    <h2 class="card-inside-title">Correo</h2>
                    <input type="email" class="form-control" name="email" placeholder='ej: ejemplo@gmail.com' value="{{$persona->email}}" />
                </div>
            </div>
            <div class="form-group">
                <div class="form-line">
                    <select class="form-control show-tick" name="departamento_id">
                        <option value="0">-- Seleccione una opcion --</option>
                        @foreach($departamentos as $departamento)
                            <option value="{{$departamento->id}}" {{ ($persona->departamento_id == $departamento->id)? 'selected':'' }}>
                                {{$departamento->nombre}}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-lg btn-block bg-black waves-effect waves-light" name="">
                GUARDAR
            </button>
        </div>
    </div>
</form>

resources/views/personas/_modal.blade.php
<div class="modal fade" id="mdModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action={{ route('personas.destroy', "-1") }} method="POST">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">¿Esta seguro que desea eliminar este Empleado?</h4>
                </div>
                <div class="modal-body"> 
                    <input type="hidden" id="id-eliminar" name="id" value="">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-link waves-effect">¡ELIMINAR!</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CERRAR</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/personas/_table.blade.php
<div class="row clearfix">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="card">
			<div class="header">
				<h2>
					Lista de Empleados
				</h2>
			</div>
			<div class="body">
				<table class="table table-bordered table-striped table-hover js-basic-example dataTable">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Apellido</th>
							<th>Cedula</th>
							<th>Email</th>
							<th>Departamento</th>
							<th>
								<a class="btn bg-teal btn-block btn-xs waves-effect" href={{route('personas.create')}}>
    								<i class="fa fa-user-plus" title="Agregar empleado"></i>
    							</a>
							</th>
						</tr>
					</thead>
					<tbody>
						@foreach($personas as $persona)
							<tr>
								<td>{{$persona->nombre}}</td>
								<td>{{$persona->apellido}}</td>
								<td>{{$persona->cedula}}</td>
								<td>{{$persona->email}}</td>
								<td>{{$persona->departamento->nombre}}</td>
								<td>
									<div class="btn-toolbar">
										<div class="btn-group btn-circle">
											<a class="btn bg-orange btn-circle waves-effect waves-circle waves-float" href={{ route('personas.edit', $persona->id) }}>
    											<i class="fa fa-edit" title="Editar empleado"></i>
    										</a>
										</div>                           
										<div class="js-modal-buttons btn-group btn-circle">
											<button value={{$persona->id}} type="button" data-color='red' class=" btn eliminar bg-red btn-circle waves-effect waves-circle waves-float ">
												<i class="fa fa-user-times" title="Eliminar empleado"></i>
											</button>
										</div>
									</div>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

resources/views/personas/create.blade.php
@extends ('template.main')
@section('title', 'Crear Empleado')
@section ('contenido')

	<!-- Input -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                        	<h1>Crear Empleado</h1>
                        </div>
                        <div class="body">
                            @include('personas._form',['departamentos' => $departamentos])
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Input -->
	
@endsection

resources/views/personas/edit.blade.php
@extends ('template.main')
@section('title', 'Editar Empleado')
@section ('contenido')

	<!-- Input -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                        	<h1>Editar Empleado</h1>
                        </div>
                        <div class="body">
                            @include('personas._form',['persona' => $persona, 'departamentos' => $departamentos])
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Input -->
	
@endsection

resources/views/personas/index.blade.php
@extends ('template.main')
@section('title', 'Lista de los empleados')
@section ('contenido')

@include('personas._modal')
@include('personas._table',[ 'personas' => $personas])
	
@endsection