app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    if(Auth::User()){
		return redirect()->route('admin.inicio');
    }else{
		return redirect()->route('auth.login');
    }
});


Route::group(['middleware' => 'auth'],function(){
	Route::get('inicio',['as' => 'admin.inicio', function () {
		return view('inicio');
	}]);

	Route::resource('usuarios','UsuarioController');
	Route::resource('departamentos','DepartamentoController');
	Route::resource('personas','PersonaController');
	Route::resource('tareas','TareasController');
	Route::resource('tareas','TareasController');
	Route::resource('detalles_tareas','Detalle_tareaController');
	Route::get('listaTareas/{id?}','TareasController@listaTareas');
	Route::get('listaTareas/{id?}', [  /*Ruta para mostrar la tabla donde se crea la tarea*/
                'uses' => 'TareasController@listaTareas',
                'as' => 'listaTareas'
                ]);
	Route::get('descarga/{id?}', [  
                'uses' => 'TareasController@descarga',
                'as' => 'descargarTarea'
                ]);
	Route::get('detalleTarea/{id?}/{opcion?}', [  
                'uses' => 'TareasController@detalleTareas',
                'as' => 'detalleTareas'
                ]);
	Route::post('correo/enviar', [  
                'uses' => 'CorreoController@enviarCorreo',
                'as' => 'enviarCorreo'
                ]);
	Route::get('correo/cargarArchivo', [ 
                'uses' => 'CorreoController@cargarArchivo',
                'as' => 'cargarArchivo'
                ]);
		Route::get('correo/nuevoCorreo', [  
                'uses' => 'CorreoController@nuevoCorreo',
                'as' => 'nuevoCorreo'
                ]);
	Route::post('actualizar', [  
                'uses' => 'CorreoController@actualizar',
                'as' => 'actualizar'
                ]);

});

Route::get('auth/login', [
	'uses' => 'Auth\AuthController@getLogin',
	'as' => 'auth.login'
]);
Route::post('auth/login', [
	'uses' => 'Auth\AuthController@postLogin',
	'as' => 'auth.login'
]);
Route::get('auth/logout', function(){
	Auth::logout();
    return redirect()->route('auth.login');
});

app/Models/Departamento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Departamento extends Model
{
    protected $table= 'departamentos';
    protected $primarykey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre','email','departamento_id'
    ];

    public function personas(){
        return $this->hasMany(Persona::class, 'departamento_id', 'id' );
    }

    public function usuarios(){
        return $this->hasMany(Persona::class, 'departamento_id', 'id' );
    }


}

app/Http/Controllers/DepartamentoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\Departamento;
use Iluminate\support\Facades\Redirect;
use sistGestion\Http\Requests\DepartamentoFormRequest;
use DB;

class DepartamentoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departamentos=Departamento::all();
        return view('departamentos.index')->with('departamentos',$departamentos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departamento = new Departamento();
        return view('departamentos.create')->with('departamento',$departamento);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Departamento::create([
                'nombre' => $request['nombre'],
                'email' => $request['email']
        ]);
        return redirect()->route('departamentos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $departamento = Departamento::findOrFail($id);
        return view('departamentos.edit')->with('departamento',$departamento);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $departamento = Departamento::FindOrFail($id);
        $input = $request->all();
        $departamento->fill($input)->save();
        return redirect()->route('departamentos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $departamento = Departamento::FindOrFail($request['id']);
        $departamento->delete();
        return redirect()->route('departamentos.index');
    }
}

resources/views/departamentos/_form.blade.php
@if ($departamento->exists)
    <form id="form-departamentos" class="" action={{ route('departamentos.update',  $departamento->id) }} method="POST">
    {{ method_field('PUT') }}
@else
    <form id="form-departamentos" class="" action={{ route('departamentos.store') }} method="POST">
@endif

    <div class="row clearfix">
        <div class="col-sm-12">
            <div class="form-group">
                <div class="form-line">
                    <h2 class="card-inside-title">Nombre</h2>
                    <input type="text" class="form-control" name="nombre" placeholder="ej: deporte" value="{{$departamento->nombre}}" required />
                </div>
            </div>
            <div class="form-group">
                <div class="form-line">
                    <h2 class="card-inside-title">Email</h2>
                    <input type="email" class="form-control" name="email" placeholder="ej: ejemplo@gmail.com" value="{{$departamento->email}}" required />
                </div>
            </div>
            <button type="submit" class="btn btn-lg btn-block bg-black waves-effect waves-light" name="">
                GUARDAR
            </button>
        </div>
    </div>
</form>

resources/views/departamentos/_modal.blade.php
<div class="modal fade" id="mdModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action={{ route('departamentos.destroy', "-1") }} method="POST">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">¿Esta seguro que desea eliminar este departamento?</h4>
                </div>
                <div class="modal-body"> 
                    <input type="hidden" id="id-eliminar" name="id" value="">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-link waves-effect">¡ELIMINAR!</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CERRAR</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/departamentos/_table.blade.php
<div class="row clearfix">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="card">
			<div class="header">
				<h2>
					Lista de departamentos
				</h2>
			</div>
			<div class="body">
				<table class="table table-bordered table-striped table-hover js-basic-example dataTable">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Correo</th>
							<th>
								<a class="btn bg-teal btn-block btn-xs waves-effect" href={{route('departamentos.create')}}>
    								<i class="fa fa-user-plus" title="Agregar departamento"></i>
    							</a>
							</th>
						</tr>
					</thead>
					<tbody>
						@foreach($departamentos as $departamento)
							<tr>
								<td>{{$departamento->nombre}}</td>
								<td>{{$departamento->email}}</td>
								<td>
									<div class="btn-toolbar">
										<div class="btn-group btn-circle">
											<a class="btn bg-orange btn-circle waves-effect waves-circle waves-float" href={{ route('departamentos.edit', $departamento->id) }}>
    											<i class="fa fa-edit" title="Editar departamento"></i>
    										</a>
										</div>                           
										<div class="js-modal-buttons btn-group btn-circle">
											<button value={{$departamento->id}} type="button" data-color='red' class=" btn eliminar bg-red btn-circle waves-effect waves-circle waves-float ">
												<i class="fa fa-user-times" title="Eliminar departamento"></i>
											</button>
										</div>
									</div>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

resources/views/departamentos/create.blade.php
@extends ('template.main')
@section('title', 'Crear departamento')
@section ('contenido')

	<!-- Input -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                        	<h1>Crear departamento</h1>
                        </div>
                        <div class="body">
                            @include('departamentos._form',['departamento'=>$departamento])
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Input -->
	
@endsection

resources/views/departamentos/edit.blade.php
@extends ('template.main')
@section('title', 'Editar Usuario')
@section ('contenido')

	<!-- Input -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                        	<h1>Editar Departamento</h1>
                        </div>
                        <div class="body">
                            @include('departamentos._form',['departamento' => $departamento])
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Input -->
	
@endsection

resources/views/departamentos/index.blade.php
@extends ('template.main')
@section('title', 'Lista de departamentos')
@section ('contenido')

@include('departamentos._modal')
@include('departamentos._table',[ 'departamentos' => $departamentos])
	
@endsection