app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    if(Auth::User()){
		return redirect()->route('admin.inicio');
    }else{
		return redirect()->route('auth.login');
    }
});


Route::group(['middleware' => 'auth'],function(){
	Route::get('inicio',['as' => 'admin.inicio', function () {
		return view('inicio');
	}]);

	Route::resource('usuarios','UsuarioController');
	Route::resource('departamentos','DepartamentoController');
	Route::resource('personas','PersonaController');
	Route::resource('tareas','TareasController');
	Route::resource('tareas','TareasController');
	Route::resource('detalles_tareas','Detalle_tareaController');
	Route::get('listaTareas/{id?}','TareasController@listaTareas');
	Route::get('listaTareas/{id?}', [  /*Ruta para mostrar la tabla donde se crea la tarea*/
                'uses' => 'TareasController@listaTareas',
                'as' => 'listaTareas'
                ]);
	Route::get('descarga/{id?}', [  
                'uses' => 'TareasController@descarga',
                'as' => 'descargarTarea'
                ]);
	Route::get('detalleTarea/{id?}/{opcion?}', [  
                'uses' => 'TareasController@detalleTareas',
                'as' => 'detalleTareas'
                ]);
	Route::post('correo/enviar', [  
                'uses' => 'CorreoController@enviarCorreo',
                'as' => 'enviarCorreo'
                ]);
	Route::get('correo/cargarArchivo', [ 
                'uses' => 'CorreoController@cargarArchivo',
                'as' => 'cargarArchivo'
                ]);
		Route::get('correo/nuevoCorreo', [  
                'uses' => 'CorreoController@nuevoCorreo',
                'as' => 'nuevoCorreo'
                ]);
	Route::post('actualizar', [  
                'uses' => 'CorreoController@actualizar',
                'as' => 'actualizar'
                ]);

});

Route::get('auth/login', [
	'uses' => 'Auth\AuthController@getLogin',
	'as' => 'auth.login'
]);
Route::post('auth/login', [
	'uses' => 'Auth\AuthController@postLogin',
	'as' => 'auth.login'
]);
Route::get('auth/logout', function(){
	Auth::logout();
    return redirect()->route('auth.login');
});

app/Models/Usuario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{
    protected $table= 'usuarios';
    protected $primarykey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password', 'tipo','departamento_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function departamento(){
        return $this->belongsTo(Departamento::class,'departamento_id', 'id');
    }
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\Usuario;
use App\Models\Departamento;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuarios=Usuario::all();
        return view('usuarios.index')->with('usuarios',$usuarios);
    }

    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $usuario = new Usuario();
        $departamentos=Departamento::all();
        return view('usuarios.create')->with('usuario', $usuario)->with('departamentos',$departamentos);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Usuario::create([
                    'email' => $request ['email'],
                    'password' => bcrypt($request ['password']),
                    'tipo' => $request['tipo'],
                    'departamento_id' => $request['departamento_id'],
                ]);
        return redirect()->route('usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $usuario = Usuario::findOrFail($id);
        $departamentos=Departamento::all();
        return view('usuarios.edit')->with('usuario',$usuario)->with('departamentos',$departamentos);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $usuario = Usuario::FindOrFail($id);
        $input = $request->all();
        $usuario->fill($input)->save();
        return redirect()->route('usuarios.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $usuario = Usuario::FindOrFail($request['id']);
        $usuario->delete();
        return redirect()->route('usuarios.index');
    }
}

resources/views/usuarios/_form.blade.php
@if ($usuario->exists)
    <form id="form-usuarios" class="" action={{ route('usuarios.update',  $usuario->id) }} method="POST">
    {{ method_field('PUT') }}
@else
    <form id="form-usuarios" class="" action={{ route('usuarios.store') }} method="POST">
@endif

    <div class="row clearfix">
        <div class="col-sm-12">
            <div class="form-group">
                <div class="form-line">
                    <h2 class="card-inside-title">Email</h2>
                    <input type="email" class="form-control" name="email" placeholder="ej: ejemplo@gmail.com" value="{{$usuario->email}}" required />
                </div>
            </div>
            @if(!($usuario->exists))
                <div class="form-group">
                    <div class="form-line">
                        <h2 class="card-inside-title">Contraseña</h2>
                        <input type="password" class="form-control" name="password" placeholder="*********" />
                    </div>
                </div>
            @endif
            <div class="form-group">
                <div class="form-line">
                    <h2 class="card-inside-title">Departamento</h2>
                    <select class="form-control show-tick" name="departamento_id">
                        <option value="0">-- Seleccione una opcion --</option>
                        @foreach($departamentos as $departamento)
                            <option value="{{$departamento->id}}" {{ ($usuario->departamento_id == $departamento->id)? 'selected':'' }}>
                                {{$departamento->nombre}}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="form-line">
                    <h2 class="card-inside-title">Tipo</h2>
                    <select class="form-control show-tick" name="tipo">
                        <option value="0">-- Seleccione una opcion --</option>
                        <option value="administrador" {{ ($usuario->tipo == 'administrador')? 'selected':'' }}>
                            administrador
                        </option>
                        <option value="personal" {{ ($usuario->tipo == 'personal')? 'selected':'' }}>
                            personal
                        </option>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-lg btn-block bg-black waves-effect waves-light" name="">
                GUARDAR
            </button>
        </div>
    </div>
</form>

resources/views/usuarios/_modal.blade.php
<div class="modal fade" id="mdModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action={{ route('usuarios.destroy', "-1") }} method="POST">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">¿Esta seguro que desea eliminar este Usuario?</h4>
                </div>
                <div class="modal-body"> 
                    <input type="hidden" id="id-eliminar" name="id" value="">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-link waves-effect">¡ELIMINAR!</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CERRAR</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/usuarios/_table.blade.php
<div class="row clearfix">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="card">
			<div class="header">
				<h2>
					Lista de Usuarios
				</h2>
			</div>
			<div class="body">
				<table class="table table-bordered table-striped table-hover js-basic-example dataTable">
					<thead>
						<tr>
							<th>Correo</th>
							<th>Tipo</th>
							<th>Departamento</th>
							<th>
								<a class="btn bg-teal btn-block btn-xs waves-effect" href={{route('usuarios.create')}}>
    								<i class="fa fa-user-plus" title="Agregar usuario"></i>
    							</a>
							</th>
						</tr>
					</thead>
					<tbody>
						@foreach($usuarios as $usuario)
							<tr>
								<td>{{$usuario->email}}</td>
								<td>{{$usuario->tipo}}</td>
								<td>{{$usuario->departamento->nombre}}</td>
								<td>
									<div class="btn-toolbar">
										<div class="btn-group btn-circle">
											<a class="btn bg-orange btn-circle waves-effect waves-circle waves-float" href={{ route('usuarios.edit', $usuario->id) }}>
    											<i class="fa fa-edit" title="Editar usuario"></i>
    										</a>
										</div>                           
										<div class="js-modal-buttons btn-group btn-circle">
											<button value={{$usuario->id}} type="button" data-color='red' class=" btn eliminar bg-red btn-circle waves-effect waves-circle waves-float ">
												<i class="fa fa-user-times" title="Eliminar usuario"></i>
											</button>
										</div>
									</div>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

resources/views/usuarios/create.blade.php
@extends ('template.main')
@section('title', 'Crear Usuario')
@section ('contenido')

	<!-- Input -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                        	<h1>Crear Usuario</h1>
                        </div>
                        <div class="body">
                            @include('usuarios._form',['usuario' => $usuario,'departamentos' => $departamentos])
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Input -->
	
@endsection

resources/views/usuarios/edit.blade.php
@extends ('template.main')
@section('title', 'Editar Usuario')
@section ('contenido')

	<!-- Input -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                        	<h1>Editar Usuario</h1>
                        </div>
                        <div class="body">
                            @include('usuarios._form',['usuario' => $usuario, 'departamentos' => $departamentos])
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Input -->
	
@endsection

resources/views/usuarios/index.blade.php
@extends ('template.main')
@section('title', 'Lista de los usuarios')
@section ('contenido')

@include('usuarios._modal')
@include('usuarios._table',[ 'usuarios' => $usuarios])
	
@endsection